---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # This should be set via the command line at runtime.
    tag: ""
    namespace: ""
    repo: ""
    remove_artifacts: true
    dry_run: false

  pre_tasks:
    - name: Ensure the ANSIBLE_GALAXY_TOKEN environment variable is set.
      fail:
        msg: ANSIBLE_GALAXY_TOKEN is not set.
      when: "lookup('env','ANSIBLE_GALAXY_TOKEN') == ''"

    - name: Ensure the ~/.ansible directory exists.
      file:
        path: ~/.ansible
        state: directory

    - name: Write the Galaxy token to ~/.ansible/galaxy_token
      copy:
        content: |
          token: {{ lookup('env','ANSIBLE_GALAXY_TOKEN') }}
        dest: ~/.ansible/galaxy_token

    - name: Remove conflicting artifacts
      file:
        path: '{{ item.path }}'
        state: absent
      loop:
        - { path: "../{{ namespace }}-k3s_roles-{{ tag }}.tar.gz" }
        - { path: "../galaxy.yml" }

  tasks:
    - name: Template out the galaxy.yml file.
      template:
        src: templates/galaxy.yml.j2
        dest: ../galaxy.yml

    - name: Build the collection.
      command: >
        ansible-galaxy collection build
        chdir=../

    - name: Publish the collection.
      command: >
        ansible-galaxy collection publish ./{{ namespace }}-k3s_roles-{{ tag }}.tar.gz
        chdir=../
      when: ( dry_run == false )

    - name: Remove artifacts after publish
      file:
        path: '{{ item.path }}'
        state: absent
      loop:
        - { path: "../{{ namespace }}-k3s_roles-{{ tag }}.tar.gz" }
        - { path: "../galaxy.yml" }
      when: ( remove_artifacts == true )