---
name: Lint
on:
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run pre-commit to lint
        uses: pre-commit/action@v2.0.3
