---
name: Publish
on:
  push:
    tags:
    - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get version
      id: version
      run: |
        VERSION=latest

        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi

        RE='^v([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$'

        if [[ $VERSION =~ $RE ]];
        then
          echo "RELEASE_VERSION=${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}" >> $GITHUB_ENV
        else
          exit -1
        fi

    - name: Injecting a dynamic Collection version
      uses: artis3n/ansible_galaxy_collection@v2
      with:
        api_key: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        galaxy_version: ${{ env.RELEASE_VERSION }}
